api_port: 3000
app_name: wallet-service

log_level: debug
log_path: ./.logs

postgresql:
  address: "postgres://postgres:yourpassword@mypostgres:5432/bank?sslmode=disable"
  # when wallet-service not in docker
  # address: "postgres://postgres:yourpassword@localhost:5432?sslmode=disable"
# debug connection: docker run -it --entrypoint /bin/sh -v ./configs/config.yaml:/root/config.yaml  wallet_service:latest

redis:
  address: "redis-stack:6379"
  password: ""
  db: 0
